version: 2
jobs:

  test:
    docker:
      - image: cirrusci/flutter:latest
    steps:
      - checkout
      - run: flutter doctor
      - run: flutter test 

  android-debug:
    docker:
        - image: cirrusci/flutter
    steps:
        - checkout
        - run: flutter -v build apk

  ios-debug:
    macos:
      xcode: "9.3.0"
    steps:
      - checkout
      - run: flutter -v build ios

workflows:
  version: 2
  
  test:
    jobs:
      - test

  build-android-debug:
    jobs:
      - android-debug

  build-ios-debug:
    jobs:
      - ios-debug


