version: 2
jobs:
  build:
    docker:
      - image: cirrusci/flutter:latest
    steps:
      - checkout
      - run: flutter doctor
      - run: flutter test 
      - run: flutter -v build apk
      - run: flutter -v build ios
